### ISSUE TITLE
Removal of Commented Code

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#1]
We have identified that there is a significant amount of commented-out code in the project repository. This can clutter the codebase, confuse developers, and make maintenance challenging. As a result, we propose removing all commented code to improve code readability and maintainability.

Suggested Solution:
Remove all commented-out code from the repository. This can be achieved through a systematic review of the codebase, identifying commented sections, and safely deleting them.

Note to Contributors:
Please review the proposed solution and provide feedback or alternative suggestions if necessary. Once a consensus is reached, we can proceed with the removal process.

**Comment by AK-47-17** [comment]
Kindly assign the issue to me.
