### ISSUE TITLE
Feat: Create signup and signin page

### ISSUE THREAD

**Issue by sakshiigdtuw** [XceeDesigns/Website#122]
### Describe the feature

Hello mentor , I want to create a sign up and sign in page . 
Kindly assign me the issue.

### Add ScreenShots

![image](https://github.com/XceeDesigns/Website/assets/154981554/1717723c-845d-4b0d-adf1-cc8861a70f37)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ParthMadhvani2** [comment]
@sakshiigdtuw complete within 3 days

**Comment by pragneshborad** [comment]
I would like to work on this issue @XceeDesigns , please assign me this issue.

**Comment by Nishant-k-sagar** [comment]
As I noticed that sign-in/sign-up page is not implemented on the website until yet.
So, I would like to work on this issue.
Kindly assign this issue to me @XceeDesigns
