### ISSUE TITLE
BUG: Adding a loading screen when submitting contact form

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Add a loading Screen b/w form is submitted and a response is returned by server.
And also add loading screen on dashboard-contact.html when data is fetched.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
PR #137 issue solved
