### ISSUE TITLE
(GSSoC'24) Fixing home page

### ISSUE THREAD

**Issue by Apurv7777** [XceeDesigns/Website#148]
### Describe the feature

Things needed to be fixed :
- Currently, on home page, navbar and the arrow at the center-bottom is not visible.

### Add ScreenShots

![image](https://github.com/XceeDesigns/Website/assets/65327303/2e493a48-bf25-48cf-8b1b-2342eaca2375)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
Elaborate more @Apurv7777

**Comment by Apurv7777** [comment]
### The following things are not visible :
![image](https://github.com/XceeDesigns/Website/assets/65327303/50fad1d3-f847-4f1f-91d3-bd2b876263a0)
![image](https://github.com/XceeDesigns/Website/assets/65327303/cc59a5e3-b1fb-489c-911f-b3877b0345a0)
![image](https://github.com/XceeDesigns/Website/assets/65327303/a10c9756-a1e7-4acb-82b8-9f511cc6cde4)

**Comment by Apurv7777** [comment]
It is not visible in chrome , but visible in Firefox, Microsoft Edge.

**Comment by XceeDesigns** [comment]
Check out : https://xceedesigns.com/

**Comment by Apurv7777** [comment]
### Still it is not properly showing.
