### ISSUE TITLE
BUG: Wrong hover text

### ISSUE THREAD

**Issue by AkhilaSunesh** [XceeDesigns/Website#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Location:** Footer of the webpage
![h](https://github.com/XceeDesigns/Website/assets/140897461/a93d477c-b097-46de-b334-d86b3d3a37f6)
### 
When we hover over the 'Instagram logo' , the text is mentioned as Dribble instead of Instagram. 
Kindly allow me to resolve this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chakrabortydeep** [comment]
Can I work on that issue ???? Please assign this task to me...
