### ISSUE TITLE
Search Bar is not looking good.

### ISSUE THREAD

**Issue by Karthikraut** [XceeDesigns/Website#16]
Search bar is not looking good please assign me this issue under GSSoC' 24.  So that I can make it good.
If u wish I can use tailwind CSS or else without it I can do it.

![Screenshot 2024-05-10 213451](https://github.com/XceeDesigns/Website/assets/130137266/99aa5781-2b2f-45b2-a5a9-2438502c2bde)

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@XceeDesigns
