### ISSUE TITLE
Feat:Improving the navbar search.

### ISSUE THREAD

**Issue by sharmi4590** [XceeDesigns/Website#164]
### Describe the feature

The navabar search is very simple , I can enhance the design.
![Screenshot (510)](https://github.com/XceeDesigns/Website/assets/102676949/53889a9a-6311-41d8-882f-d89e8728957f)

### Add ScreenShots

Here is my previous work.

https://github.com/XceeDesigns/Website/assets/102676949/e2b8ac5d-98e5-4eaa-9a39-71df7ec28ef6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
Hii @sharmi4590 ,
Just a small suggestion don't go for full screen searchbar and make sure your proposed design aligns with our website theme

**Comment by sharmi4590** [comment]
@XceeDesigns Done , I will follow ur suggestions.
