### ISSUE TITLE
Add login and signup page.

### ISSUE THREAD

**Issue by Sneha123-zudo** [XceeDesigns/Website#170]
### Describe the feature

I want to add login and signup page to the website.

### Add ScreenShots

<img width="517" alt="image" src="https://github.com/XceeDesigns/Website/assets/145490348/8d0160c7-e6b3-48e0-811f-0d9c39f83ba5">

Please assign me this issue under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Tanishka023** [comment]
> ### Describe the feature
> 
> I want to add login and signup page to the website.
> 
> ### Add ScreenShots
> 
> <img width="517" alt="image" src="https://github.com/XceeDesigns/Website/assets/145490348/8d0160c7-e6b3-48e0-811f-0d9c39f83ba5">
> 
> Please assign me this issue under GSSOC'24
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Hey!! Please assign this issue to me under GSSoC'24 , I can do this easily @XceeDesigns
