### ISSUE TITLE
NOT GOOD for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [XceeDesigns/Website#174]
### Describe the feature

The website is not proper on mobile screen.

I should be fixed to improve the user experience on all devices.
I would love to contribute to this project.

### Add ScreenShots

![image](https://github.com/XceeDesigns/Website/assets/124615886/a58394f1-c798-4096-ae02-db2e2c72afe6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
@ParthMadhvani2 check this again,
Attached SS is not from XceeDesgins Web page

**Comment by ParthMadhvani2** [comment]
sorry by mistake I have not seen SS.
