### ISSUE TITLE
Sign Up and Login Pages

### ISSUE THREAD

**Issue by Syed0206** [XceeDesigns/Website#19]
I would like to add Sign up and Login Pages to the website @XceeDesigns please assign me this issue under GSSOC'24

**Comment by tusharyadav11** [comment]
In my earlier projects i have worked on sign up and login pages of website. i would be grateful if you could assign this task to me @Syed0206

**Comment by dhanushsurendra** [comment]
I can make visually appealing sign up and login pages. Please assign me this isssue

**Comment by XceeDesigns** [comment]
not required!
