### ISSUE TITLE
Feat: Improve SEO of the Home Page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [XceeDesigns/Website#199]
### Describe the feature

I will improve the SEO (Search Engine Optmization ) of the home page currently the seo score of the website it 50 i can increase it to 65-70

### Add ScreenShots

![Screenshot 2024-06-09 100502](https://github.com/XceeDesigns/Website/assets/118350936/0c51a68c-80db-48e6-a9b5-b5a1a03ba9a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
Hii @Ayushmaanagarwal1211 ,
Add relevant keywords as well, so that website appears in search with different keywords i.e xceed designs, Xceedesigns, XceeDesigns, Website Development and for other related keywords as well.

**Comment by Ayushmaanagarwal1211** [comment]
Sure

**Comment by XceeDesigns** [comment]
@Ayushmaanagarwal1211 Any update ?

**Comment by Ayushmaanagarwal1211** [comment]
@XceeDesigns  Yes yes actually i am busy with exams finishing on 16 so please wait till 16 i will surely raise pr for that

**Comment by XceeDesigns** [comment]
@Ayushmaanagarwal1211 Updates ?
