### ISSUE TITLE
Implement Modal for Contact Us Submit Button

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#2]
Currently, when users submit their contact information through the "Contact Us" form, there's no visual feedback to confirm the successful submission. To enhance user experience and provide feedback, we should implement a modal that appears upon successful submission, acknowledging that the contact information has been sent successfully.

Additional Considerations:

1. Ensure the modal design aligns with the project's UI/UX guidelines.
2. Test the modal functionality across different browsers and devices to ensure compatibility.
3. Consider any accessibility concerns to ensure all users can interact with the modal effectively.

Acceptance Criteria:

1. The modal should appear upon successful submission of the "Contact Us" form.
2. The modal should display a success message confirming the submission.
3. Users should be able to close the modal by clicking on the close button (×) or anywhere outside the modal.
4. The modal design should be visually appealing and consistent with the project's design language.

Related Files/Components:
Contact.html

**Comment by venom-2** [comment]
Kindly assign this issue to me!!
