### ISSUE TITLE
Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [XceeDesigns/Website#206]
### Describe the feature

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Add ScreenShots

Preview of proposed Website Visitor widget:

![Screenshot 2024-06-12 143634](https://github.com/XceeDesigns/Website/assets/113301503/377fde4f-6770-4bc8-8647-a7dfcc04092b)

**Please assign this issue to me under the gssoc label**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
Not required
