### ISSUE TITLE
Feat: Submit contact us form using Enter on keyboard

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#208]
### Describe the feature

NA

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Saimanjari777** [comment]
I want to work on this issue. Please assign this issue to me @XceeDesigns

**Comment by Saimanjari777** [comment]
I am working on it. I will make pr tomorrow

**Comment by UtkarshBirla28** [comment]
Sir i want to work on this issue. Please assign this issue to me @XceeDesigns

**Comment by XceeDesigns** [comment]
@Saimanjari777 Update plz otherwise i'll assign this issue to @UtkarshBirla28

**Comment by UtkarshBirla28** [comment]
> @Saimanjari777 Update plz otherwise i'll assign this issue to @UtkarshBirla28

yessss

**Comment by UtkarshBirla28** [comment]
@XceeDesigns  is this issue resolved ? or else assign it to me i will try to reslove it ASAP.
