### ISSUE TITLE
Feat: Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [XceeDesigns/Website#213]
### Describe the feature

A preloader is an essential feature for enhancing user experience by indicating the progress of loading content. It helps in keeping the users engaged while the main content is being fetched or rendered. Implementing a preloader can significantly improve the perceived performance of our application.

### Add ScreenShots

My Previous Works:-

https://github.com/XceeDesigns/Website/assets/146121869/971bafd7-9357-4414-a9fb-f013cd63027c

https://github.com/XceeDesigns/Website/assets/146121869/e1fab3c2-4b41-4d55-bd7d-1c4c8376ddbd

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
Have you visited https://xceedesigns.com ? @AsmitaMishra24 
Because we are already having lazy loading in our website.
