### ISSUE TITLE
BUG:This search button is irrelavent it doesn't do anything.Whenever u search something and press enter curent page get's reloaded.

### ISSUE THREAD

**Issue by UtkarshBirla28** [XceeDesigns/Website#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
This search button is irrelavent it doesn't do anything.Whenever u search something and press enter curent page get's reloaded

![Screenshot (70)](https://github.com/XceeDesigns/Website/assets/96072228/5b4693a8-e6a4-43bb-b59d-dafbf80908e7)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ash-k121** [comment]
I can fix this.
