### ISSUE TITLE
Improving Code Commenting Standards and Practices

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#22]
As our project grows in complexity and scope, it becomes increasingly important to maintain clear and informative code comments. This issue aims to establish and refine standards and practices for commenting throughout our codebase.

We need to address several aspects, including:

1. Consistency: Ensure uniformity in commenting style and formatting across all modules and files.
2. Clarity: Review existing comments to guarantee they effectively explain code functionality, intent, and rationale.
3. Completeness: Identify areas lacking sufficient comments and add them to enhance code comprehension and maintainability.
4. Update and Maintenance: Implement a strategy for regularly updating comments to reflect changes in code functionality or architecture.
5. Documentation: Discuss the integration of external documentation tools or platforms to supplement in-code comments for broader project understanding.

This issue will serve as a centralized discussion and coordination point for improving our code commenting practices, fostering better collaboration and understanding among team members and contributors.

**Comment by sakshii00** [comment]
Please assign this issue to me under GSSOC'24
