### ISSUE TITLE
SEO Optimization Improvement for Project

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#26]
Search Engine Optimization (SEO) plays a crucial role in ensuring that our project is easily found by potential users, contributors, and stakeholders. By optimizing the project repository for SEO, we can increase organic traffic, enhance our online presence, and attract more collaborators.

Expected Outcome:

- Improved search engine rankings for relevant keywords related to our project.
- Increased organic traffic to our project.
- Enhanced visibility and discoverability within the Internet

**Comment by kairveeehh** [comment]
as a person who has freelanced for SEO optimisation I would like to take up this issue @XceeDesigns  
## please assign under gssoc'24

**Comment by kairveeehh** [comment]
> @kairveeehh Any updates ?

you just rejected an issue after 3 days of work I did and responsivness , I am sorry I wont like to work under your project .

**Comment by XceeDesigns** [comment]
Thanks for your feedback @kairveeehh , but your contribution is not aligning with your requirements.

Best of luck for future contributions on this or other projects.

**Comment by haard18** [comment]
Would like to contribute to this

**Comment by haard18** [comment]
I would be following google's seo optimization guide for this @XceeDesigns 
https://developers.google.com/search/docs/fundamentals/seo-starter-guide
