### ISSUE TITLE
Re-arranging Content for Correct Ordering of Work Process

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#3]
It appears there's a discrepancy in the workflow order for our landing page. The correct sequence should be as follows:
Planning -> Designing -> Development -> Deployment

Mobile View : 
![image](https://github.com/XceeDesigns/Website/assets/165802815/2912d79d-c0b9-47cf-af7b-c053ea1ebc18)

Desktop View : 
![image](https://github.com/XceeDesigns/Website/assets/165802815/e60acd35-d215-4844-8e95-90b3cc44a9d7)

**Comment by mikekellyonline** [comment]
I would like to work on this.
