### ISSUE TITLE
About-Us page can be added

### ISSUE THREAD

**Issue by AtharvKasar04** [XceeDesigns/Website#32]
An about-us page can be added which will include about the website `XceeDesigns` like, Introduction, Story, etc

@XceeDesigns Can i work on this issue under GSSoC'24. I would love to work on this addition.
Thank You!

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor.

**Comment by hritika2409** [comment]
@XceeDesigns Thank you so much for assigning me this work. Please give me some time, I will get back to you in couple of days with the assigned work.

**Comment by hritika2409** [comment]
@XceeDesigns Hey i have completed my assigned task .Please do check it.

**Comment by hritika2409** [comment]
@XceeDesigns hey?
