### ISSUE TITLE
Adding animation by framer motion

### ISSUE THREAD

**Issue by Adeesh-bode** [XceeDesigns/Website#33]
We're looking to add some cool animations to our website using Framer Motion, a popular tool for smooth, easy-to-implement animations in React apps. The goal is to spruce up things like button clicks, page transitions, and pop-ups to make the user experience more dynamic and fun. We need to make sure these animations look great across all devices without slowing things down. Let’s keep things slick without compromising on performance!

Straggering effects in child elements
elements entry by animation

**Comment by Adeesh-bode** [comment]
Hey, I reviewed the project and noticed that the animations are already quite good. Therefore, I looked for other issues and found that the accessibility of the dashboard needs improvement. Additionally, the logo redirection is not following the standard practice of redirecting to the homepage. I worked on enhancing the dashboard's accessibility and updated the logo redirection to point to the home page (index.html). The newsletter section also seemed lacking in content, so I added some meaningful and explanatory content to improve it. I am raising the pr , please review it. Thanks, consider this contribution in girlscript summer of code

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@XceeDesigns
