### ISSUE TITLE
Dashboard Unreachable: Inclusion of navlink for dashboard in navbar. ( instead of just keeping its navigation on click of  logo in navbar )

### ISSUE THREAD

**Issue by Adeesh-bode** [XceeDesigns/Website#37]
The issue involves making the dashboard more accessible by including a dedicated navigation link (navlink) for it in the navbar, instead of limiting its access to a click on the logo. This enhancement aims to improve user navigation and make it easier for users to find and access the dashboard directly through a clear, visible link in the navigation bar. The task would involve updating the navbar layout to include a new navlink, ensuring it is properly integrated and functional, and testing to confirm that it leads directly to the dashboard with appropriate user authentication checks, if necessary.

**Comment by XceeDesigns** [comment]
Hii @Adeesh-bode 
Dashboard is only for admins, thus we dont need any specific nav link for that but you can work on auth part of dashboard and enhancing UI/UX part as well.
You can simply add a Login form for Admin, after centain checks dashboard details should appear, make sure your create UI aligns with our theme.

Happy Coding

**Comment by XceeDesigns** [comment]
Not required!
