### ISSUE TITLE
Removing unnecessary spacing in the project , which will improve ui

### ISSUE THREAD

**Issue by Adeesh-bode** [XceeDesigns/Website#38]
The issue involves optimizing the user interface of a project by removing unnecessary spacing throughout various components and layouts. This improvement is aimed at enhancing the visual coherence and user experience of the website or application by creating a more streamlined, tidy appearance. The task would include reviewing and adjusting the CSS properties related to margins, padding, and other spacing elements across different sections, ensuring that the adjustments do not affect the responsiveness or accessibility of the site.
Example: Removal of Spacing in footer

**Comment by Amitooo1** [comment]
Hey @XceeDesigns can i work on this issue? Please assign me under gssoc.

**Comment by XceeDesigns** [comment]
@Adeesh-bode Any updates ?

**Comment by Adeesh-bode** [comment]
I will raise pr in 2hrs.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@XceeDesigns
