### ISSUE TITLE
Click to open location on map

### ISSUE THREAD

**Issue by pankaj-bind** [XceeDesigns/Website#42]
### Describe the feature

I can implement a feature so that if user click on Address. it will redirect him to google map to the given location.

### Add ScreenShots

![image](https://github.com/XceeDesigns/Website/assets/73558583/206cc218-9a84-482c-b3c4-08ad445688c6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
@pankaj-bind Any updates ?

**Comment by pankaj-bind** [comment]
> @pankaj-bind Any updates ?

In next 10 minute
