### ISSUE TITLE
Enhancing the footer of the landing  page 

### ISSUE THREAD

**Issue by Omi006** [XceeDesigns/Website#43]
### Describe the feature

Enhancing the footer component of website, so it will look good.

### Add ScreenShots

like this, I will customize so it will look appealing to website.
![Screenshot 2024-05-12 112820](https://github.com/XceeDesigns/Website/assets/113918394/8df3a2bd-8869-4d97-8b80-e6c7d27883f7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by curecode11** [comment]
![image](https://github.com/XceeDesigns/Website/assets/118065498/710190b3-424c-4457-be2b-31fce8deae92)
Please assign the task to me i can make responsive designs

**Comment by XceeDesigns** [comment]
Not required!
