### ISSUE TITLE
{Enhancement] Recreate Landing Page Design Using React

### ISSUE THREAD

**Issue by atharvmalve** [XceeDesigns/Website#45]
### Description:
Our website's landing page lacks interactivity and adaptability. To enhance user experience and streamline development, I propose remaking the current design using React.js.

### Problem:
- Static landing page lacks engagement and flexibility.
- Current design inhibits future updates and optimizations.

### Proposed Solution:
Recreate the landing page design in React.js to introduce interactivity and modularity while maintaining the existing aesthetics.

### Tasks:
1. Analyze current design and extract key elements.
2. Plan and design a React component-based structure.
3. Implement React components to mirror the current layout.
4. Ensure responsiveness and cross-device compatibility.
5. Test functionality and optimize codebase.

### Expected Benefits:
- Improved user engagement with dynamic elements.
- Streamlined development process with React's modularity.
- Facilitated future updates and enhancements.

### Additional Notes:
This task is a subpart of Issue #23 and <b> will be completed in a separate branch</b>. The name/link to the branch will be provided soon. I request the admin to assign this task to me. Looking forward to enhancing our landing page with React.

**Comment by XceeDesigns** [comment]
Add new branch in our repo and start working on it name it "XceeDesigns-Frontend"
