### ISSUE TITLE
[Enchancement] Recreate Services Page in React 

### ISSUE THREAD

**Issue by atharvmalve** [XceeDesigns/Website#46]
### Description:
In our ongoing pursuit of improving user experience, we aim to recreate the services page using React.js. This task, part of Issue #23, invites contributions to enhance our website's functionality and visual appeal.

### Proposed Solution:
Recreate the services page design in React.js while preserving the existing layout. Focus on implementing animation for a mobile phone element to enrich user interaction. Utilize Tailwind CSS for modular code and seamless responsiveness.

### Tasks:
1. Analyze the current services page layout and identify key elements.
2. Design a React component-based structure to mirror the existing layout.
3. Implement animation for the mobile phone element on scroll.
4. Ensure web responsiveness using Tailwind CSS.
5. Test functionality across devices and optimize codebase.
6. Contribute changes to a separate branch (branch name to be provided soon).

### Expected Benefits:
- Enhanced user experience with interactive elements.
- Streamlined development process with React's component-based approach.
- Improved website responsiveness with Tailwind CSS.

### Additional Notes:
This task aims to improve user experience by recreating the services page in React and adding animation for enhanced engagement. Contributions from the community are welcome. Please contribute changes to the designated branch (branch name to be provided soon). Let's collaborate to create a more captivating and user-friendly website.

**Comment by vasundhara943** [comment]
As a contributor for GSSOC'24 with ample experience in ReactJS development using Tailwind CSS, I would like to work on this issue. Please assign the same to me as you see fit.

**Comment by XceeDesigns** [comment]
@vasundhara943  You just need to convert service page in react and for that get in touch with @atharvmalve .
make sure react code should be pushed on XceeDesgins-Frontend branch only.

If you are ready to work under certain rules i can assigns this issue to you

**Comment by vasundhara943** [comment]
Sure, I would like to work on this issue, please assign the same to me and explain the rules mentioned.
@atharvmalve please let me know how we can discuss and collaborate on this issue, as I see this requires collaborating with other contributors working on similar pages.

**Comment by atharvmalve** [comment]
hey @vasundhara943  congratulations on getting assigned for this issue! Lets connect on discord (my id: @learningmonkk).

**Comment by XceeDesigns** [comment]
@vasundhara943 Any update ?

**Comment by vasundhara943** [comment]
@XceeDesigns Yes sir it's in progress. I will give you a proper update by tomorrow EOD, is that fine?

**Comment by XceeDesigns** [comment]
Absolutely fine @vasundhara943

**Comment by XceeDesigns** [comment]
@vasundhara943 Any update ?

**Comment by vasundhara943** [comment]
> @vasundhara943 Any update ?

Sorry sir, I have my endsems going on till 5th June, so I have not been able to give a good amount of time to this issue. I will work on it after 5th, is that alright?

**Comment by XceeDesigns** [comment]
@vasundhara943 AKTU ? 
Alright all the best for your exams👍
