### ISSUE TITLE
Enhancement: Recreation of Footer in React

### ISSUE THREAD

**Issue by hars-21** [XceeDesigns/Website#61]
### Describe the feature

For enhancing user experience, I want to enhance footer UI to industry standards where user can easily navigate to other parts of website.

Also adding industry standard features like contact form, maybe a location map and other social media icons for user to easily contact the organisation.

some footer images are attached for reference. 
** These are only for reference, actual design will be specific to website **

### Add ScreenShots

![Screen Shot 2024-05-13 at 8 47 01 PM](https://github.com/XceeDesigns/Website/assets/144909381/d28115e8-0387-40a9-bfd7-76dff2f81c33)
![Screen Shot 2024-05-13 at 8 47 23 PM](https://github.com/XceeDesigns/Website/assets/144909381/ebe8b6d1-7f5a-4eef-85b0-4809564636e1)
![Screen Shot 2024-05-13 at 8 47 38 PM](https://github.com/XceeDesigns/Website/assets/144909381/940e833b-aa0e-433b-a6f5-d0e3746e7ebe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Tanishka023** [comment]
Hey!! Please assign this issue to me under GSSoC'24 , I can do this easily @XceeDesigns
