### ISSUE TITLE
Feat: Adding and improving lets work together link

### ISSUE THREAD

**Issue by Stiffpixels** [XceeDesigns/Website#65]
### Describe the feature

- Adding a call to action link on the __homepage__ will make the navigation a lot easier for the users and might increase sales for the business. 
- Adding a hover effect to the connect button to make it pop and grab the attention of the visitors.
 

### Add ScreenShots

it can be added like the one below with hover effects as mentioned.
![image](https://github.com/XceeDesigns/Website/assets/32983571/5955a558-d049-4500-ad64-9ca871f80006)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
@Stiffpixels can you plz add a video for the same issue just for the clarification.

**Comment by Stiffpixels** [comment]
> @Stiffpixels can you plz add a video for the same issue just for the clarification.

as you can see there is no call to action button on the home page or lets connect button:

https://github.com/XceeDesigns/Website/assets/32983571/0c66b40f-fcfd-4a9e-8661-74bc105614bf

**Comment by XceeDesigns** [comment]
Hii @Stiffpixels ,
You can work in this, but remember this PR will only be merged after approving it with our inhouse team.

Happy Coding!
