### ISSUE TITLE
Feat: Make a responsive footer with all the hyperlinks to navigate in and around the site.

### ISSUE THREAD

**Issue by curecode11** [XceeDesigns/Website#66]
### Describe the feature

Use of pure html,css and javascript is enough to make a modern footer section which will go with the current aesthetics of the website.

### Add ScreenShots

I will make these type of footer keeping the current design in my mind
![image](https://github.com/XceeDesigns/Website/assets/118065498/55569c8c-fe74-494f-978c-2c7eefb111f7)
**please assign me this task for the GSSOC'24**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by LalithKumar77** [comment]
Dear @XceeDesigns , 
            i have already made the new footer design with responsiveness .
