### ISSUE TITLE
About us page missing 

### ISSUE THREAD

**Issue by NitinChakrawarti** [XceeDesigns/Website#68]
### Describe the feature

Currently website doesn't have have any about us page, i can create a responsive about us page for website.
@mikekellyonline  please assign this issue to i want to work on it .

### Add ScreenShots

![Screenshot 2024-05-14 203856](https://github.com/XceeDesigns/Website/assets/149225785/eee2233a-23e5-4c9c-b0ca-9e814cb99d48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pragneshborad** [comment]
I would like to work on this issue @XceeDesigns , please assign me this issue.
