### ISSUE TITLE
Search bar Suggestions

### ISSUE THREAD

**Issue by lakshyajn** [XceeDesigns/Website#7]
Hey, It is little advance for me, but I'll try my best

I just need to know about the search database you have to make suggestions accordingly.

@sanjay-kv 
**##Please Assign It To Me**

**Comment by officialhemant511** [comment]
hey @sanjay-kv can u pls assign this issue to me ...

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor. @sanjay-kv 

**Record**

- [ ]  I agree to follow this project's Code of Conduct
- [ ]  I'm a GSSOC'24 contributor
- [ ]  I want to work on this issue
