### ISSUE TITLE
DOC: update index.html

### ISSUE THREAD

**Issue by harshagarwal0401** [XceeDesigns/Website#78]
### Update Index.html

I have seen the code and seen that we can add comments in the index.html file making the code more informative.

### Add ScreenShots

![screenshot index html xceedesigns](https://github.com/XceeDesigns/Website/assets/132535945/9d4fe30b-9f37-4360-a2d8-126ad3a512b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nileshsn** [comment]
Assign me I will also work on this issue under GSSOC24.
