### ISSUE TITLE
FOOTER UPDATE

### ISSUE THREAD

**Issue by Gauranshgoel123** [XceeDesigns/Website#79]
### Describe the feature

As shown in the below ss, whole part can be merged into the footer to make it more appealing and be available on each page of the website

### Add ScreenShots

![image](https://github.com/XceeDesigns/Website/assets/121503835/2504f33d-7ded-4cf9-9608-c9bc2c4a3597)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor.

**Comment by LalithKumar77** [comment]
Subject: Proposal to Contribute Footer Design 

Dear @XceeDesigns ,

 My name is Lalith Kumar, and I'm enthusiastic about contributing to Xcee Designs as part of the GSSoC program.

After exploring the project's repository on GitHub, I noticed an opportunity to enhance the overall user experience by revamping the footer design. A well-designed footer can significantly improve navigation and provide valuable information to users.

Please assign this task to me  and also assign tag GSSoC 24 tag to this issue.

![Screenshot 2024-05-16 142610](https://github.com/XceeDesigns/Website/assets/163830157/504eb7e0-95e1-4561-865e-c94f32ffcad5)

**Comment by XceeDesigns** [comment]
@LalithKumar77 Happy to see you here,
Your proposed design is cool, but unfortunately it is not aligning with our theme.
Still i am assigning you with this issue hoping you can re-design or tailer it according to our theme.

Happy Coding!

**Comment by 000626574705** [comment]
can i change footer for better please assign me

**Comment by LalithKumar77** [comment]
Dear @XceeDesigns ,

i made the new footer design which is aligned to the website theme 
if it is ok i am ready make PR  
![Screenshot 2024-05-17 192909](https://github.com/XceeDesigns/Website/assets/163830157/000dd362-2a52-42cd-8345-56a7066763d9)

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@XceeDesigns

**Comment by LalithKumar77** [comment]
Hello @XceeDesigns  I made a pull request based on this issue please check it out

**Comment by LalithKumar77** [comment]
Hi @XceeDesigns ,

I noticed my pull request for footer updates (#PR number) was closed. Could you please provide some feedback on why it was closed? I'm happy to make any necessary changes to get it merged.
