### ISSUE TITLE
Alignment of the section

### ISSUE THREAD

**Issue by kairveeehh** [XceeDesigns/Website#8]
@sanjay-kv  hello , 
would like to fix this bug of the section not being centred - small but a UI issue

## please assign this issue to me under gssoc'24
![Screenshot 2024-05-09 194043](https://github.com/XceeDesigns/Website/assets/145572028/a69e5e45-6349-4bc5-9eb8-59e6ab1016e9)

**Comment by michellecordovi** [comment]
Please assign this issue to me as I would like to contribute under GSSoC'24 . I can fix this issue!

**Comment by PayalKumari10** [comment]
@XceeDesigns  i would to like to work on this . please assign it to me

**Comment by XceeDesigns** [comment]
Irrelevent Issue

**Comment by kairveeehh** [comment]
> Irrelevent Issue

@XceeDesigns but it was assigned to me and that is why I worked over it
