### ISSUE TITLE
Updat : Upgrading Images on services page

### ISSUE THREAD

**Issue by XceeDesigns** [XceeDesigns/Website#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/XceeDesigns/Website/assets/165802815/9b2e7324-f1f6-4047-b9d6-4c55a24a029f)
![image](https://github.com/XceeDesigns/Website/assets/165802815/25318f4e-07b7-4993-a2a2-82b62009b1b2)
 Changing these images into more professional ones.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by haard18** [comment]
I would Like to  Contribute to this @XceeDesigns

**Comment by Jaishree-baskaran** [comment]
I would like to contribute my solution to this issue. Please assign it to me.

**Comment by haard18** [comment]
I am working on it @Jaishree-baskaran

**Comment by sanskritisahu21** [comment]
I would like to contribute on this issue under Gssoc'24. Please assign me the issue.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@XceeDesigns
