### ISSUE TITLE
BUG: Images in Services Page are colliding with the navbar

### ISSUE THREAD

**Issue by haard18** [XceeDesigns/Website#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am observing that the mobile phone image is overlapping the header which would give a really bad UI Experience 
![image](https://github.com/XceeDesigns/Website/assets/128149378/42859b96-66f0-4c2d-bb04-df088e0bc77a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by XceeDesigns** [comment]
It's a feature btw
Not required!
