### ISSUE TITLE
Enhanc: add animations to the footer 

### ISSUE THREAD

**Issue by sau-mili** [XceeDesigns/Website#94]
![Screenshot 2024-05-19 184845](https://github.com/XceeDesigns/Website/assets/146661411/36ebaf78-cab6-4d92-962a-70e4f23b0b6d)

Add animations here
N.B: I am a GSSOC contributor

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@XceeDesigns
